import Link from 'next/link';
import {userDb} from '@/lib/supabase/server';
import {FollowButton} from '@/components/member-controls';
import Image from 'next/image';
import {notFound} from 'next/navigation';
import {getCatalog,gamePath,arcPath,chapterPath,media} from '@/lib/catalog';
import {Breadcrumb,Rating} from '@/components/content';
import {ChevronRight,ArrowRight} from 'lucide-react';
export default async function GamePage({params,searchParams}:{params:Promise<{gameSlug:string}>;searchParams:Promise<{story?:string}>}){
 const {gameSlug}=await params;const data=await getCatalog();const game=data.games.find(x=>x.slug===gameSlug);if(!game)notFound();
 const db=await userDb();const {data:{user}}=await db.auth.getUser();const follow=user?await db.from('game_follows').select('game_id').eq('user_id',user.id).eq('game_id',game.id).maybeSingle():null;
 const selected=(await searchParams).story==='event'?'event':'main';
 const arcs=data.arcs.filter(x=>x.game_id===game.id);const stats=data.gameStats.find(x=>x.id===game.id);
 const mainArcs=arcs.filter(x=>x.story_kind!=='event');const eventArcs=arcs.filter(x=>x.story_kind==='event');const visibleArcs=selected==='event'?eventArcs:mainArcs;
 return <div className="page-shell"><Breadcrumb items={[{label:'게임',href:'/games'},{label:game.title}]}/><section className="game-hero"><Image src={media(game.hero_image)} alt="" fill sizes="100vw" priority/><div><span className="eyebrow">GAME COLLECTION</span><h1>{game.title}</h1><p>{game.description||'한 장씩 만나는 이야기, 그 안에서 빛나는 캐릭터.'}</p><Rating average={stats?.average} count={stats?.count}/></div></section><div className="game-follow-row"><FollowButton gameId={game.id} initial={!!follow?.data} signedIn={!!user}/></div><nav className="tabs"><a href="#intro">소개</a><a href="#arcs" className="active">스토리 목록</a><Link href={`${gamePath(game)}/characters`}>캐릭터</Link><Link href={`${gamePath(game)}/stats`}>평가 통계</Link></nav><section id="intro" className="intro-line"><p>메인 스토리 {mainArcs.length}개 편과 이벤트 {eventArcs.length}개를 둘러보세요.</p><Link href={`${gamePath(game)}/characters`}>캐릭터 모아보기 <ArrowRight size={16}/></Link></section><section id="arcs"><nav className="story-filters" aria-label="스토리 구분"><Link href={`${gamePath(game)}?story=main#arcs`} aria-current={selected==='main'?'page':undefined}>메인 <span>({mainArcs.length})</span></Link><span aria-hidden="true">/</span><Link href={`${gamePath(game)}?story=event#arcs`} aria-current={selected==='event'?'page':undefined}>이벤트 <span>({eventArcs.length})</span></Link></nav>{!visibleArcs.length&&<p className="empty-state">아직 공개된 {selected==='event'?'이벤트':'메인 스토리'}가 없습니다.</p>}<div className="arc-list">{visibleArcs.map(arc=>{const eventChapter=arc.story_kind==='event'?data.chapters.find(x=>x.arc_id===arc.id):undefined;const target=eventChapter?chapterPath(data,eventChapter):arcPath(game,arc);const stat=data.arcStats.find(x=>x.id===arc.id);return <article className="arc-row" key={arc.id}><Link href={target} className="arc-row-image"><Image src={media(arc.cover_image)} alt={arc.title} width={640} height={450}/></Link><div className="arc-row-copy"><Link href={target}><h2>{arc.title}</h2></Link><p>{arc.summary}</p><Rating average={stat?.average} count={stat?.count}/>{arc.story_kind!=='event'&&<div className="chapter-shortcuts">{data.chapters.filter(x=>x.arc_id===arc.id).map(chapter=><Link href={chapterPath(data,chapter)} key={chapter.id}><span className="chapter-number">{chapter.sort_order}장</span><span>{chapter.title}</span><ChevronRight size={15}/></Link>)}</div>}{eventChapter&&<Link className="text-button" href={target}>이벤트 스토리 보기 <ChevronRight size={15}/></Link>}</div></article>;})}</div></section></div>;
}
