import Link from 'next/link';
import Image from 'next/image';
import {notFound} from 'next/navigation';
import {getCatalog,gamePath,arcPath,chapterPath,media} from '@/lib/catalog';
import {Breadcrumb,Rating,SectionTitle} from '@/components/content';
import {ChevronRight,ArrowRight} from 'lucide-react';
export default async function GamePage({params}:{params:Promise<{gameSlug:string}>}){
 const {gameSlug}=await params;const data=await getCatalog();const game=data.games.find(x=>x.slug===gameSlug);if(!game)notFound();
 const arcs=data.arcs.filter(x=>x.game_id===game.id);const stats=data.gameStats.find(x=>x.id===game.id);
 return <div className="page-shell"><Breadcrumb items={[{label:'게임',href:'/games'},{label:game.title}]}/><section className="game-hero"><Image src={media(game.hero_image)} alt="" fill sizes="100vw" priority/><div><span className="eyebrow">GAME COLLECTION</span><h1>{game.title}</h1><p>{game.description||'한 장씩 만나는 이야기, 그 안에서 빛나는 캐릭터.'}</p><Rating average={stats?.average} count={stats?.count}/></div></section><nav className="tabs"><a href="#intro">소개</a><a href="#arcs" className="active">편 목록</a><Link href={`${gamePath(game)}/characters`}>캐릭터</Link></nav><section id="intro" className="intro-line"><p>{arcs.length}개의 편, {data.chapters.filter(x=>x.game_id===game.id).length}개의 공개된 장을 둘러보세요.</p><Link href={`${gamePath(game)}/characters`}>캐릭터 모아보기 <ArrowRight size={16}/></Link></section><section id="arcs"><SectionTitle title="편 목록" count={arcs.length}/><div className="arc-list">{arcs.map(arc=>{const stat=data.arcStats.find(x=>x.id===arc.id);return <article className="arc-row" key={arc.id}><Link href={arcPath(game,arc)} className="arc-row-image"><Image src={media(arc.cover_image)} alt={arc.title} width={640} height={450}/></Link><div className="arc-row-copy"><Link href={arcPath(game,arc)}><h2>{arc.title}</h2></Link><p>{arc.summary}</p><Rating average={stat?.average} count={stat?.count}/><div className="chapter-shortcuts">{data.chapters.filter(x=>x.arc_id===arc.id).map(chapter=><Link href={chapterPath(data,chapter)} key={chapter.id}><span className="chapter-number">{chapter.sort_order}장</span><span>{chapter.title}</span><ChevronRight size={15}/></Link>)}</div></div></article>;})}</div></section></div>;
}
