'use client';
import {useState,useRef} from 'react';
import Image from 'next/image';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {ArrowLeft,ArrowRight,ChevronRight,Users} from 'lucide-react';
import type {Chapter,Character} from '@/lib/catalog';
import {Reviews} from './reviews';
const media=(path:string|null)=>path?'/media/'+path.split('/').map(encodeURIComponent).join('/'):'/placeholder.svg';
type Props={chapter:Chapter;characters:Character[];initialCharacter?:string;chapters:{id:string;title:string;url:string;order:number}[];characterBase:string;ratingsEnabled:boolean;commentsEnabled:boolean};
export function ChapterExperience({chapter,characters,initialCharacter,chapters,characterBase,ratingsEnabled,commentsEnabled}:Props){
 const router=useRouter();const [selected,setSelected]=useState(characters.find(c=>c.slug===initialCharacter)?.id??characters[0]?.id??'');const [expanded,setExpanded]=useState(false);const scroller=useRef<HTMLDivElement>(null);const drag=useRef<{x:number;left:number;moved:boolean}|null>(null);
 const person=characters.find(c=>c.id===selected);const index=chapters.findIndex(c=>c.id===chapter.id);
 return <><nav className="chapter-navigator" aria-label="장 이동">{index>0?<Link href={chapters[index-1].url}><ArrowLeft size={16}/><span>이전 장</span></Link>:<span className="nav-disabled"><ArrowLeft size={16}/>이전 장</span>}<select aria-label="장 선택" value={chapter.id} onChange={e=>router.push(chapters.find(c=>c.id===e.target.value)!.url)}>{chapters.map(c=><option key={c.id} value={c.id}>{c.order}장 · {c.title}</option>)}</select>{index<chapters.length-1?<Link href={chapters[index+1].url}><span>다음 장</span><ArrowRight size={16}/></Link>:<span className="nav-disabled">다음 장<ArrowRight size={16}/></span>}</nav><div className="chapter-layout"><article className="chapter-story"><Image className="chapter-art" src={media(chapter.detail_image)} alt={chapter.title} width={1280} height={900} priority/><div className="chapter-copy"><div className="eyebrow blue">CHAPTER {String(chapter.sort_order).padStart(2,'0')}<span>{chapter.release_date_kr?.replaceAll('-','.')}</span></div><h1>{chapter.title}</h1><p>{chapter.summary||'줄거리를 준비하고 있어요.'}</p></div><Reviews key={chapter.id} chapter={chapter.id} title="이 장의 평가" ratingsEnabled={ratingsEnabled} commentsEnabled={commentsEnabled}/></article><aside className="character-panel"><div className="section-title"><h2><Users size={18}/>이번 장의 등장 캐릭터 <span>{characters.length}</span></h2><button className="text-button" onClick={()=>setExpanded(x=>!x)} aria-expanded={expanded}>{expanded?'접기':'전체 보기'}</button></div><div className={`character-selector ${expanded?'expanded':''}`} ref={scroller}
 onWheel={e=>{const el=scroller.current;if(!expanded&&el&&el.scrollWidth>el.clientWidth&&e.deltaY!==0){el.scrollLeft+=e.deltaY;}}}
 onPointerDown={e=>{if(e.pointerType==='mouse'&&scroller.current)drag.current={x:e.clientX,left:scroller.current.scrollLeft,moved:false};}}
 onPointerMove={e=>{if(drag.current&&scroller.current){const delta=e.clientX-drag.current.x;if(Math.abs(delta)>5)drag.current.moved=true;scroller.current.scrollLeft=drag.current.left-delta;}}}
 onPointerUp={()=>{setTimeout(()=>{drag.current=null;},0);}} onPointerLeave={()=>{drag.current=null;}}>
 {characters.map(c=><button key={c.id} onClick={()=>{if(!drag.current?.moved)setSelected(c.id);}} className={selected===c.id?'selected':''} aria-pressed={selected===c.id} aria-label={`${c.name} 선택`}><Image src={media(c.thumbnail)} alt="" width={128} height={128} draggable={false}/><span>{c.name.split(' ').at(-1)}</span></button>)}</div>{person?<div key={person.id}><div className="selected-character"><Image src={media(person.image)} alt={person.name} width={512} height={512}/><div><span className="eyebrow">CHARACTER</span><h2>{person.name}</h2>{person.description&&<p>{person.description}</p>}<Link href={`${characterBase}/${person.slug}`}>캐릭터의 다른 이야기 <ChevronRight size={14}/></Link></div></div><Reviews chapter={chapter.id} character={person.id} title="이번 장에서의 캐릭터 평가" ratingsEnabled={ratingsEnabled} commentsEnabled={commentsEnabled}/></div>:<p className="empty-state">등장 캐릭터를 준비하고 있어요.</p>}</aside></div></>;
}
