'use client';
import {useEffect,useState,useCallback} from 'react';
import Link from 'next/link';
import {Star,ThumbsUp,MessageCircle} from 'lucide-react';
import {saveRating,saveComment,deleteComment,likeComment} from '@/app/actions';
type Comment={id:string;user_id:string;body:string;is_spoiler:boolean;display_name:string;like_count:number;created_at:string};
type ReviewData={comments:Comment[];total:number;summary:{average:number;count:number}|null;distribution:{score:number;count:number}[];myRating:number|null;myComment:{id:string;body:string;is_spoiler:boolean}|null;userId:string|null;liked:string[]};
export function Reviews({chapter,character=null,title,ratingsEnabled,commentsEnabled}:{chapter:string;character?:string|null;title:string;ratingsEnabled:boolean;commentsEnabled:boolean}){
 const [data,setData]=useState<ReviewData|null>(null);const [score,setScore]=useState(0);const [body,setBody]=useState('');const [spoiler,setSpoiler]=useState(false);const [sort,setSort]=useState('likes');const [page,setPage]=useState(0);const [revision,setRevision]=useState(0);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [message,setMessage]=useState('');const [loadError,setLoadError]=useState('');
 useEffect(()=>{const controller=new AbortController();setLoading(true);setLoadError('');const params=new URLSearchParams({chapter,sort,page:String(page)});if(character)params.set('character',character);
 fetch('/api/reviews?'+params,{signal:controller.signal}).then(async r=>{const json=await r.json();if(!r.ok)throw new Error(json.error);return json as ReviewData;}).then(json=>{setData(json);setScore(json.myRating??0);setBody(json.myComment?.body??'');setSpoiler(json.myComment?.is_spoiler??false);setLoading(false);}).catch(e=>{if(e.name!=='AbortError'){setLoadError(e.message);setLoading(false);}});return()=>controller.abort();},[chapter,character,sort,page,revision]);
 const act=useCallback(async(action:()=>Promise<{ok:boolean;error?:string}>,success:string)=>{setBusy(true);setMessage('');try{const result=await action();setMessage(result.ok?success:result.error||'다시 시도해 주세요.');if(result.ok)setRevision(x=>x+1);}catch{setMessage('연결이 끊겼어요. 다시 시도해 주세요.');}finally{setBusy(false);}},[]);
 const count=data?.summary?.count??0;const signedIn=!!data?.userId;
 return <div className="reviews"><section className="rating-section"><div className="mini-label">{title}</div><div className="score-summary"><Star size={26} fill="currentColor"/><strong>{count?Number(data?.summary?.average).toFixed(1):'—'}</strong><span>/ 5.0</span></div><p className="muted">{count?`${count.toLocaleString()}개의 평가`:'첫 번째 감상을 기다리고 있어요.'}</p>{count>0&&<div className="distribution" aria-label="평점 분포">{[5,4,3,2,1].map(n=>{const amount=(data?.distribution??[]).filter(x=>Math.ceil(Number(x.score))===n).reduce((s,x)=>s+Number(x.count),0);return <div key={n}><span>{n}점</span><div><i style={{width:`${amount/count*100}%`}}/></div><span>{Math.round(amount/count*100)}%</span></div>;})}</div>}
 <p className="rating-question">{character?'이번 장에서 이 캐릭터는 어땠나요?':'이 장의 이야기는 어땠나요?'}</p><div className="stars" aria-hidden="true">{[1,2,3,4,5].map(n=><span key={n} style={{'--fill':`${Math.max(0,Math.min(1,score-n+1))*100}%`} as React.CSSProperties}>★</span>)}</div><label className="score-control"><span>내 별점</span><select aria-label="내 별점" value={score} onChange={e=>setScore(Number(e.target.value))} disabled={!signedIn||!ratingsEnabled||busy||loading}><option value={0}>선택해 주세요</option>{Array.from({length:10},(_,i)=>(i+1)/2).map(value=><option value={value} key={value}>{value.toFixed(1)}점</option>)}</select><button className="button small" disabled={!signedIn||!score||!ratingsEnabled||busy||loading} onClick={()=>act(()=>saveRating(chapter,character,score),'평가를 저장했어요.')}>평가 저장</button></label>{!ratingsEnabled&&<p className="muted">평가 등록을 잠시 쉬고 있어요.</p>}{!signedIn&&!loading&&<Link className="login-prompt" href="/login">로그인하고 평가와 한줄평 남기기 <span>→</span></Link>}</section>
 <section className="comment-section"><div className="section-title"><h2>한줄평 <span>{data?.total??0}</span></h2><select aria-label="한줄평 정렬" value={sort} onChange={e=>{setSort(e.target.value);setPage(0);}}><option value="likes">좋아요순</option><option value="new">최신순</option></select></div>{signedIn&&commentsEnabled&&<form className="comment-composer" onSubmit={e=>{e.preventDefault();act(()=>saveComment(chapter,character,body,spoiler),'한줄평을 저장했어요.');}}><textarea aria-label="한줄평 내용" placeholder="어떤 장면이 기억에 남았나요?" value={body} onChange={e=>setBody(e.target.value)} maxLength={300} disabled={busy||loading}/><div className="composer-bottom"><label><input type="checkbox" checked={spoiler} onChange={e=>setSpoiler(e.target.checked)}/>이후 장 스포일러 포함</label><span>{body.length}/300</span></div><div className="composer-actions">{data?.myComment&&<button className="text-button" type="button" disabled={busy||loading} onClick={()=>act(()=>deleteComment(data.myComment!.id),'한줄평을 삭제했어요.')}>삭제</button>}<button className="button small" disabled={busy||loading||!body.trim()}>{data?.myComment?'한줄평 수정':'한줄평 등록'}</button></div></form>}{!commentsEnabled&&<p className="muted">한줄평 등록을 잠시 쉬고 있어요.</p>}
 {loading&&<p role="status" className="muted">감상을 불러오는 중…</p>}{loadError&&<p role="alert" className="form-error">{loadError}<button className="text-button" onClick={()=>setRevision(x=>x+1)}>다시 시도</button></p>}{message&&<p role="status" className="form-message">{message}</p>}{!loading&&!loadError&&!data?.comments.length&&<div className="comments-empty"><MessageCircle size={23}/><p>아직 남겨진 한줄평이 없어요.</p></div>}{!loadError&&data?.comments.map(comment=><article className="comment" key={comment.id}><div className="comment-top"><span className="profile-initial">{comment.display_name.slice(0,1)}</span><strong>{comment.display_name}</strong><time>{comment.created_at.slice(0,10).replaceAll('-','.')}</time></div>{comment.is_spoiler?<details className="spoiler"><summary>이후 장 스포일러가 포함되어 있어요 · 보기</summary><p>{comment.body}</p></details>:<p>{comment.body}</p>}<button className={`like-button ${data.liked.includes(comment.id)?'liked':''}`} disabled={!signedIn||busy||loading||!commentsEnabled} aria-pressed={data.liked.includes(comment.id)} onClick={()=>act(()=>likeComment(comment.id,data.liked.includes(comment.id)),'좋아요를 반영했어요.')}><ThumbsUp size={14}/>{comment.like_count}</button></article>)}{(data?.total??0)>20&&<div className="pagination"><button disabled={page===0||loading} onClick={()=>setPage(x=>x-1)}>이전</button><span>{page+1} / {Math.ceil((data?.total??0)/20)}</span><button disabled={(page+1)*20>=(data?.total??0)||loading} onClick={()=>setPage(x=>x+1)}>다음</button></div>}</section></div>;
}
