import Link from 'next/link';
import {Search,ArrowUpRight} from 'lucide-react';
import {getCatalog,gamePath,arcPath,chapterPath,characterPath} from '@/lib/catalog';
import {Empty} from '@/components/content';
export const metadata={title:'이야기 검색'};
export default async function SearchPage({searchParams}:{searchParams:Promise<{q?:string}>}){
 const {q=''}=await searchParams;const query=q.trim().slice(0,100);const data=await getCatalog();const matches=(value:string)=>!!query&&value.toLocaleLowerCase().includes(query.toLocaleLowerCase());
 const groups=[{label:'게임',items:data.games.filter(x=>matches(x.title)).map(x=>({id:x.id,title:x.title,context:'게임',url:gamePath(x)}))},{label:'편',items:data.arcs.filter(x=>matches(x.title)).map(x=>({id:x.id,title:x.title,context:data.games.find(g=>g.id===x.game_id)!.title,url:arcPath(data.games.find(g=>g.id===x.game_id)!,x)}))},{label:'장',items:data.chapters.filter(x=>matches(x.title+' '+data.arcs.find(a=>a.id===x.arc_id)?.title+' '+x.sort_order+'장')).map(x=>({id:x.id,title:x.title,context:`${data.arcs.find(a=>a.id===x.arc_id)!.title} · ${x.sort_order}장`,url:chapterPath(data,x)}))},{label:'캐릭터',items:data.characters.filter(x=>matches(x.name)).map(x=>({id:x.id,title:x.name,context:data.games.find(g=>g.id===x.game_id)!.title,url:characterPath(data.games.find(g=>g.id===x.game_id)!,x)}))}];
 return <div className="page-shell search-page"><div className="page-heading"><span className="eyebrow blue">FIND YOUR STORY</span><h1>기억에 남은 이야기를 찾아보세요</h1></div><form className="search-form" action="/search"><Search size={21}/><input name="q" defaultValue={query} placeholder="게임, 편, 장, 캐릭터 검색" aria-label="검색어" maxLength={100}/><button className="button">검색</button></form>{query?<><p className="search-count">“{query}” 검색 결과 <strong>{groups.reduce((n,g)=>n+g.items.length,0)}</strong>건</p>{groups.map(group=><section className="search-group" key={group.label}><h2>{group.label}<span>{group.items.length}</span></h2>{group.items.length?group.items.map(item=><Link key={item.id} href={item.url}><span className="search-kind">{group.label}</span><div><h3>{item.title}</h3><p>{item.context}</p></div><ArrowUpRight size={18}/></Link>):<p className="muted">검색 결과가 없어요.</p>}</section>)}</>:<Empty>이름이나 이야기 제목으로 검색하면 해당 페이지로 바로 이동할 수 있어요.</Empty>}</div>;
}
